### PR TITLE
[fix #9] Reproduce double spend and check if Edge weight calculator w…

### LINKED ISSUE #9: Reproduce double spend and check if Edge weight calculator works
Double spend problem should be addressed and reproduced as the benchmark to help us improve or solve this problem. We need a unit test to achieve this goal.

### Description
1) Write the unit test to reproduce the double spend problem;
2) check the effectiveness of the edge weight calculator versus vertex weight calculator.

### Motivation
Solve the double spend issue in IOTA.

### Requirements
N/A

### Open Questions (optional)
N/A

### Am I planning to do it myself with a PR?
Yes.

### PR DESCRIPTION
**Pull request by stplaydog**

### CODE REVIEW

File: src/main/java/com/iota/iri/service/tipselection/impl/CumulativeWeightWithEdgeCalculator.java [hunk 1]
```diff
@@ -106,7 +114,15 @@ private long preprocessDatas(Map<String, Long> edgeMap, Map<Hash, Set<Hash>> app
...
-			float edgeWeight = (float) edgeMap.get(txHash.toString() + prover.toString()) / maxTimeDiff;
+                        float edgeWeight = 0;
+                        if(isUseUnifiedEdgeWeight)
+                        {
+                            edgeWeight = 1; 
+                        }
+                        else
+                        {
+                            edgeWeight = (float) edgeMap.get(txHash.toString() + prover.toString()) / maxTimeDiff;
+                        }
```
Comment (niming2100) [inline src/main/java/com/iota/iri/service/tipselection/impl/CumulativeWeightWithEdgeCalculator.java:120]: In java , we are not used to write '{' in a new line . The code can be optimized ,just like below. We don't need to assign 'edgeWeight' twice no matter  the 'isUseUnifiedEdgeWeight' is true or not
float edgeWeight = 1;
if(!isUseUnifiedEdgeWeight) {
    edgeWeight = (float) edgeMap.get(txHash.toString() + prover.toString()) / maxTimeDiff;
}

Comment (stplaydog) [reply src/main/java/com/iota/iri/service/tipselection/impl/CumulativeWeightWithEdgeCalculator.java:120]: thanks, done

**Review by niming2100 — APPROVED** [review]
